// Cenário fictício: sexta-feira, 9 de outubro de 2026, às 23h30.
const photo = (id, width = 800) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const artists = [
  { name: 'Vintage Culture', image: photo('photo-1571266028243-d220c9b3b157',300) },
  { name: 'Marina Reis', image: photo('photo-1516280440614-37939bbacd81',300) },
  { name: 'DJ Luma', image: photo('photo-1487180144351-b8472da7d491',300) },
  { name: 'Coletivo Frequência', image: photo('photo-1506157786151-b8491531f063',300) },
  { name: 'Caio Bossa', image: photo('photo-1511192336575-5a79af67a629',300) }
];
const events = [
  { id:'subsolo', name:'Além da meia-noite', venue:'Subsolo Club', district:'Vila Madalena', address:'Rua Harmonia, 520', time:'23:00 — 05:00', artist:'Vintage Culture', price:null, status:'Aberto agora', occupancy:null, distance:null, category:'Festas', day:'today', date:'09 OUT', weekday:'SEX', tickets:false, image:photo('photo-1470229722913-7c0e2dbbafd3'), description:'Uma noite para perder a noção do tempo. House envolvente, uma pista intimista e um encontro com a música até o sol chegar.' },
  { id:'terraco', name:'Uma noite lá em cima', venue:'Terraço 011', district:'Pinheiros', address:'Rua dos Pinheiros, 870', time:'19:00 — 02:00', artist:'DJ Luma', price:null, status:'Últimos ingressos', occupancy:null, distance:null, category:'Bares', day:'today', date:'09 OUT', weekday:'SEX', tickets:false, image:photo('photo-1514933651103-005eec06c04b'), description:'Drinks autorais, disco e a cidade vista de outro ângulo. Encontre os amigos no terraço e deixe a noite acontecer.' },
  { id:'jazz', name:'Jazz à meia-luz', venue:'Sótão Jazz Bar', district:'Vila Buarque', address:'Rua General Jardim, 210', time:'20:00 — 02:00', artist:'Caio Bossa', price:null, status:'Aberto agora', occupancy:null, distance:null, category:'Música ao vivo', day:'today', date:'09 OUT', weekday:'SEX', tickets:false, image:photo('photo-1511192336575-5a79af67a629'), description:'Jazz, brasilidades e boas conversas. Uma sessão ao vivo em um pequeno refúgio da cidade, com luz baixa e som de perto.' },
  { id:'frequencia', name:'Frequência independente', venue:'Casa Aurora', district:'Barra Funda', address:'Rua Vitorino Carmilo, 430', time:'22:00 — 04:00', artist:'Coletivo Frequência', price:null, status:'Aberto agora', occupancy:null, distance:null, category:'Shows', day:'today', date:'09 OUT', weekday:'SEX', tickets:false, image:photo('photo-1506157786151-b8491531f063'), description:'Novos sons ocupam a Casa Aurora em uma celebração da cena independente. Entrada gratuita, sujeita à capacidade da casa.' },
  { id:'groove', name:'Into the groove', venue:'Audio Club', district:'Água Branca', address:'Av. Francisco Matarazzo, 694', time:'22:00 — 06:00', artist:'Vintage Culture', price:null, status:'Começa em breve', occupancy:null, distance:null, category:'Festas', day:'tomorrow', date:'10 OUT', weekday:'SÁB', tickets:false, image:photo('photo-1571266028243-d220c9b3b157'), description:'Uma pista, muitas conexões. Uma seleção de house e techno para atravessar a madrugada.' },
  { id:'soul', name:'Soul sessions', venue:'Casa de Francisca', district:'Sé', address:'Rua Quintino Bocaiúva, 22', time:'20:00 — 01:00', artist:'Marina Reis', price:null, status:'Esgotado', occupancy:null, distance:null, category:'Música ao vivo', day:'tomorrow', date:'10 OUT', weekday:'SÁB', tickets:false, image:photo('photo-1516280440614-37939bbacd81'), description:'Uma apresentação intimista de soul e R&B no coração do centro histórico.' },
  { id:'domingo', name:'Domingo em vinil', venue:'Pátio Discos', district:'Pinheiros', address:'Rua Artur de Azevedo, 980', time:'17:00 — 23:00', artist:'DJ Luma', price:null, status:'Fechado', occupancy:null, distance:null, category:'Bares', day:'weekend', date:'11 OUT', weekday:'DOM', tickets:false, image:photo('photo-1487180144351-b8472da7d491'), description:'Seleção em vinil, mesas na calçada e uma trilha sonora para encerrar o fim de semana sem pressa.' },
  { id:'patio', name:'Encontros no pátio', venue:'Casa Aurora', district:'Barra Funda', address:'Rua Vitorino Carmilo, 430', time:'16:00 — 22:00', artist:'Coletivo Frequência', price:null, status:'Encerrado', occupancy:null, distance:null, category:'Shows', day:'past', date:'08 OUT', weekday:'QUI', tickets:false, image:photo('photo-1506157786151-b8491531f063'), description:'Uma tarde de shows e encontros que já deixou saudade. Acompanhe as próximas edições na Casa Aurora.' }
];