<?php
declare(strict_types=1);
check((bool)getenv('NIGHTOUT_TEST_RUN'), 'catalog tests isolated');
$db->exec('DELETE FROM auth_limits');
$client = curl_init(); curl_setopt($client, CURLOPT_COOKIEFILE, '');
check(request('/api/v1/admin/venues')[0] === 401, 'anonymous cannot read admin catalog');
check(request('/api/v1/admin/venues/photo','POST',[])[0] === 401, 'anonymous cannot upload');
$public = request('/api/v1/venues')[1]['venues'];
check(count($public) === 31 && $public[0]['image'] === 'assets/venues/supra-direito-fachada.webp', 'all 31 researched records imported with photos');
check(importCatalog($db) === 0, 'catalog import is idempotent');
$csrf = request('/api/v1/auth/me')[1]['csrf'];
$email = 'catalog-' . getenv('NIGHTOUT_TEST_RUN') . '@nightout.invalid';
$password = bin2hex(random_bytes(12));
putenv('NIGHTOUT_CATALOG_TEST_PASSWORD=' . $password);
$result=request('/api/v1/auth/register','POST',['name'=>'Catalog Admin','email'=>$email,'password'=>$password],$csrf)[1];
$csrf=$result['csrf'];
$userId=$result['user']['id'];
check(request('/api/v1/admin/venues')[0] === 403,'ordinary unverified user cannot read admin catalog');
$db->prepare("UPDATE users SET role='admin' WHERE id=?")->execute([$userId]);
check(request('/api/v1/admin/venues')[0] === 403,'unverified admin cannot read catalog');
$db->prepare("UPDATE users SET role='user',email_verified_at=NOW() WHERE id=?")->execute([$userId]);
check(request('/api/v1/admin/venues')[0] === 403,'verified ordinary user cannot read catalog');
$db->prepare("UPDATE users SET role='admin' WHERE id=?")->execute([$userId]);
$records=request('/api/v1/admin/venues')[1]['records'];
$record=$records[0]; $original=$record['venue'];
$input=$original+['published'=>false,'revision'=>$record['revision']];
check(request('/api/v1/admin/venues','POST',$input)[0]===403,'admin writes require CSRF');
$input['name']='Edited place';
$edited=request('/api/v1/admin/venues','POST',$input,$csrf);
check($edited[0]===200 && $edited[1]['record']['revision']===2,'admin can edit and hide with revision');
check(count(request('/api/v1/venues')[1]['venues'])===30,'hidden venue absent from public API');
check(request('/api/v1/admin/venues','POST',$input,$csrf)[0]===409,'stale edit cannot overwrite newer record');
check(importCatalog($db)===0 && count(request('/api/v1/venues')[1]['venues'])===30,'reimport does not restore hidden venues');
$input['revision']=2;
$input['weeklyHours']=[[['25:00','02:00']],[],[],[],[],[],[]];
check(request('/api/v1/admin/venues','POST',$input,$csrf)[0]===422,'invalid hours rejected');
$input['weeklyHours']=$original['weeklyHours'];
$input['officialUrl']='javascript:alert(1)';
check(request('/api/v1/admin/venues','POST',$input,$csrf)[0]===422,'unsafe URL rejected');
$input['officialUrl']=$original['officialUrl'];$input['coordinates']=['latitude'=>100,'longitude'=>0];
check(request('/api/v1/admin/venues','POST',$input,$csrf)[0]===422,'invalid coordinates rejected');
$input['coordinates']=$original['coordinates'];$input['published']=true;$input['name']=$original['name'];
$restored=request('/api/v1/admin/venues','POST',$input,$csrf);
check($restored[0]===200 && count(request('/api/v1/venues')[1]['venues'])===31,'admin can republish');
check($restored[1]['record']['venue']['popularTimes']===$original['popularTimes'],'editing preserves researched graphs');
// Upload uses real multipart HTTP and the private test image directory.
$photoFile=dirname(__DIR__).'/assets/venues/supra-direito-fachada.webp';
curl_setopt_array($client,[CURLOPT_URL=>$base.'/api/v1/admin/venues/photo',CURLOPT_CUSTOMREQUEST=>'POST',
    CURLOPT_POSTFIELDS=>['photo'=>new CURLFile($photoFile,'image/webp','photo.webp')],CURLOPT_HTTPHEADER=>['X-CSRF-Token: '.$csrf]]);
$photoResponse=json_decode(curl_exec($client),true);
check(curl_getinfo($client,CURLINFO_RESPONSE_CODE)===201 && isset($photoResponse['image']),'real photo decoded and reencoded');
check(request($photoResponse['image'])[0]===200,'uploaded image served by restricted media route');
curl_setopt_array($client,[CURLOPT_URL=>$base.'/api/v1/admin/venues/photo',CURLOPT_CUSTOMREQUEST=>'POST',
    CURLOPT_POSTFIELDS=>['photo'=>new CURLFile(__FILE__,'image/png','fake.png')],CURLOPT_HTTPHEADER=>['X-CSRF-Token: '.$csrf]]);
curl_exec($client);
check(curl_getinfo($client,CURLINFO_RESPONSE_CODE)===422,'disguised PHP photo rejected');
$input['id']='';$input['name']='New catalog fixture';$input['published']=false;$input['photo']=$photoResponse;
$created=request('/api/v1/admin/venues','POST',$input,$csrf);
check($created[0]===200 && str_starts_with($created[1]['record']['venue']['id'],'local-'),'new venue and uploaded photo saved');
check(count(request('/api/v1/venues')[1]['venues'])===31,'new draft hidden by default');
$db->prepare('UPDATE venues SET document=? WHERE id=?')->execute([json_encode($original,JSON_UNESCAPED_UNICODE),$original['id']]);
